{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 version: "3.8\
services:\
\'a0 sonarqube:\
\'a0 \'a0 image: sonarqube\
\'a0 \'a0 depends_on:\
\'a0 \'a0 \'a0 - postgres_sonar\
\'a0 \'a0 ports:\
\'a0 \'a0 \'a0 - "9000:9000"\
\'a0 \'a0 networks:\
\'a0 \'a0 \'a0 - sonar-network\
\'a0 \'a0 environment:\
\'a0 \'a0 \'a0 SONAR_JDBC_URL: jdbc:postgresql://postgres_sonar:5432/sonar\
\'a0 \'a0 \'a0 SONAR_JDBC_USERNAME: sonar\
\'a0 \'a0 \'a0 SONAR_JDBC_PASSWORD: sonar\
\'a0 \'a0 volumes:\
\'a0 \'a0 \'a0 - sonarqube_data:/opt/sonarqube/data\
\'a0 \'a0 \'a0 - sonarqube_extensions:/opt/sonarqube/extensions\
\'a0 \'a0 \'a0 - sonarqube_logs:/opt/sonarqube/logs\
\'a0 \'a0 \'a0 - sonarqube_temp:/opt/sonarqube/temp\
\'a0 postgres_sonar:\
\'a0 \'a0 image: postgres\
\'a0 \'a0 networks:\
\'a0 \'a0 \'a0 - sonar-network\
\'a0 \'a0 environment:\
\'a0 \'a0 \'a0 POSTGRES_USER: sonar\
\'a0 \'a0 \'a0 POSTGRES_PASSWORD: sonar\
\'a0 \'a0 \'a0 POSTGRES_DB: sonar\
\'a0 \'a0 volumes:\
\'a0 \'a0 \'a0 - pgdata:/var/lib/postgresql/data\'a0 \'a0 \'a0\
\
\
networks:\
\'a0 sonar-network:\
\'a0 \'a0 driver: bridge\
\
\
volumes:\
\'a0 sonarqube_data:\
\'a0 sonarqube_extensions:\
\'a0 sonarqube_logs:\
\'a0 sonarqube_temp:\
\'a0 pgdata:\'a0"\
}