-- Script generated by Marcio Jose Santana RA 19102877-5
-- Disciplina: Banco de Dados II 52/2021
-- Atividade 01: Engenharia de Software    Version: 1.0

/* Criando o Banco de Dados do Sistema Bos Covid19 (Bussines On-line Sistem Covid19)*/
CREATE SCHEMA IF NOT EXISTS bos_covid19;


/* Criação de Tabelas */
Use bos_covid19;

CREATE TABLE IF NOT EXISTS tipo_local (
	idtipo_local int not null auto_increment, 
    hospital Varchar(45), 
    clinica varchar(45), 
    UPA varchar(45),
    local_atendimento_idlocal_atendimento int not null unique,
    local_atendimento_medico_idmedico int not null unique,
    constraint pk_idtipolocal primary key(idtipo_local)) engine= InnoDB;
     
CREATE TABLE IF NOT EXISTS local_atendimento (
	idlocal_atendimento int not null auto_increment,
    medico_idmedico int not null,
    nome varchar(50),
    cnpj int not null,
    telefone varchar(10),
    constraint pk_atendimento primary key(idlocal_atendimento,medico_idmedico))engine= InnoDB;
   
CREATE TABLE IF NOT EXISTS medico (
	idmedico int not null auto_increment ,
	nome varchar(150) not null,
    funcao varchar(45) not null,
    localM varchar(10) not null,
    turno varchar(45),
    telefone varchar(45),
    constraint pk_idmedico primary key (idmedico))engine= InnoDB;
    
CREATE TABLE IF NOT EXISTS funcao (
	idfuncao int not null auto_increment ,
    medico varchar(45),
    enfermeiro varchar(45),
    zelador varchar(45),
    medico_idmedico int not null unique,
    constraint pk_idfuncao primary key(idfuncao))engine= InnoDB;
    
CREATE TABLE IF NOT EXISTS endereco (
	rua varchar(15),
    numero int(8) not null,
    bairro varchar(20),
    cep varchar(8),
    cidade varchar(20),
    paciente_idpaciente int not null unique,
    local_atendimento_idlocal_atendimento int not null unique,
    local_atendimento_medico_idmedico int not null unique,
    medico_idmedico int not null unique)engine= InnoDB;
  
CREATE TABLE IF NOT EXISTS exame (
	idexame int not null auto_increment,
    resultado varchar(45),
    paciente_idpaciente int not null unique,
    medico_idmedico int not null unique,
    constraint pk_idexame primary key (idexame))engine= InnoDB;
      
CREATE TABLE IF NOT EXISTS diagnostico (
	iddiagnostico int not null auto_increment,
    status varchar(1),
    prontuario_idprontuario int not null unique,
    constraint pk_iddiagnostico primary key (iddiagnostico))engine= InnoDB;
       
CREATE TABLE IF NOT EXISTS prontuario (
	idprontuario int not null auto_increment,
	origem_paciente varchar(45),
    locais_atedimento varchar(45),
    paciente_idpaciente int not null unique,
    paciente_local_atendimento_idlocal_atendimento int not null unique,
    paciente_local_atendimento_medico_idmedico int not null unique,
    constraint pk_idprontuario primary key(idprontuario))engine= InnoDB;
    
CREATE TABLE IF NOT EXISTS paciente (
	idpaciente int not null,
	nome varchar(150),
	cpf int not null,
	telefone int not null,
    medico_idmedico int not null unique,
    local_atendimento_idlocal_atendimento int not null,
    local_atendimento_medico_idmedico int not null,
    constraint pk_idpaciente primary key (idpaciente,local_atendimento_idlocal_atendimento,local_atendimento_medico_idmedico))engine= InnoDB;
    
 CREATE TABLE IF NOT EXISTS pessoa_con (
	paciente int not null unique,
	nome varchar(150))engine= InnoDB;
    
 /* Criando Chaves Estrangeiras */

 ALTER TABLE bos_covid19.tipo_local add constraint pk_local_atendimento_tipo_local foreign key (local_atendimento_idlocal_atendimento,local_atendimento_medico_idmedico) references bos_covid19.local_atendimento (idlocal_atendimento,medico_idmedico);
 ALTER TABLE bos_covid19.local_atendimento add constraint pk_medico_local_atendim foreign key (medico_idmedico) references bos_covid19.medico (idmedico);
 ALTER TABLE bos_covid19.funcao add constraint pk_idmedico_funcao foreign key (medico_idmedico) references bos_covid19.medico(idmedico);
 ALTER TABLE bos_covid19.endereco add constraint pk_paciente_endereco foreign key (paciente_idpaciente) references bos_covid19.paciente(idpaciente);
 ALTER TABLE bos_covid19.endereco add constraint pk_medico_endereco foreign key (medico_idmedico) references bos_covid19.medico(idmedico);
 ALTER TABLE bos_covid19.endereco add constraint pk_local_atendimento_idlocal_endereco foreign key (local_atendimento_idlocal_atendimento,local_atendimento_medico_idmedico) references bos_covid19.local_atendimento (idlocal_atendimento,medico_idmedico);
 ALTER TABLE bos_covid19.exame add constraint pk_paciente_exame foreign key (paciente_idpaciente) references bos_covid19.paciente(idpaciente);
 ALTER TABLE bos_covid19.exame add constraint pk_paciente_exame_medico foreign key (medico_idmedico) references bos_covid19.medico(idmedico);
 ALTER TABLE bos_covid19.diagnostico add constraint pk_prontuario_diagnostico foreign key (prontuario_idprontuario) references bos_covid19.prontuario(idprontuario);
 ALTER TABLE bos_covid19.prontuario add constraint pk_paciente_idpaciente_prontuario foreign key (paciente_idpaciente) references bos_covid19.paciente(idpaciente);
 ALTER TABLE bos_covid19.prontuario add constraint pk_paciente_local_atendimento_idlocal_prontuario foreign key (paciente_local_atendimento_idlocal_atendimento,paciente_local_atendimento_medico_idmedico) references bos_covid19.local_atendimento (idlocal_atendimento,medico_idmedico);
 ALTER TABLE bos_covid19.paciente add constraint pk_medico_idmedico foreign key (medico_idmedico) references bos_covid19.medico(idmedico);
 ALTER TABLE bos_covid19.paciente add constraint pk_paciente_local_atendimento_idlocal_paciente foreign key (local_atendimento_idlocal_atendimento,local_atendimento_medico_idmedico) references bos_covid19.local_atendimento (idlocal_atendimento,medico_idmedico);
 ALTER TABLE bos_covid19.pessoa_con add constraint pk_pacienteid_pessoa_con foreign key (paciente) references bos_covid19.paciente(idpaciente);

/*
CREATE USER 'sha2user'@'localhost'
IDENTIFIED WITH caching_sha2_password BY 'password';

SET SQL_SAFE_UPDATES = 0
*/


