-- MySQL Script generated by MySQL Workbench
-- Sat Jun 26 21:04:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcli` INT NOT NULL,
  `rgdi` INT NOT NULL,
  `cpfid` VARCHAR(11) NOT NULL,
  `nmdi` VARCHAR(45) NULL,
  `enddi` VARCHAR(45) NULL,
  PRIMARY KEY (`idcli`),
  UNIQUE INDEX `cpfid_UNIQUE` (`cpfid` ASC) VISIBLE,
  UNIQUE INDEX `idcli_UNIQUE` (`idcli` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `idmar` INT NOT NULL,
  `dsmar` VARCHAR(45) NOT NULL,
  `obsmar` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idmar`),
  UNIQUE INDEX `idmar_UNIQUE` (`idmar` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `idmod` INT NOT NULL,
  `dsmod` VARCHAR(45) NULL,
  `obsmod` VARCHAR(150) NULL,
  `marca_idmar` INT NOT NULL,
  PRIMARY KEY (`idmod`),
  UNIQUE INDEX `idmod_UNIQUE` (`idmod` ASC) VISIBLE,
  INDEX `fk_modelo_marca1_idx` (`marca_idmar` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_idmar`)
    REFERENCES `mydb`.`marca` (`idmar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idfornecedor` INT NOT NULL,
  `cnpjfor` VARCHAR(14) NOT NULL,
  `razbr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  UNIQUE INDEX `idfor_UNIQUE` (`idfornecedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idpro` INT NOT NULL,
  `dspro` VARCHAR(45) NULL,
  `obsrpro` VARCHAR(150) NULL,
  `modelo_idmod` INT NOT NULL,
  `fornecedor_idbr` INT NOT NULL,
  PRIMARY KEY (`idpro`),
  UNIQUE INDEX `idpro_UNIQUE` (`idpro` ASC) VISIBLE,
  INDEX `fk_produto_modelo_idx` (`modelo_idmod` ASC) VISIBLE,
  INDEX `fk_prduto_fornecedor1_idx` (`fornecedor_idbr` ASC) VISIBLE,
  CONSTRAINT `fk_produto_modelo`
    FOREIGN KEY (`modelo_idmod`)
    REFERENCES `mydb`.`modelo` (`idmod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prduto_fornecedor1`
    FOREIGN KEY (`fornecedor_idbr`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_copy1` (
  `idvenda` INT NOT NULL,
  `cliente_iddi` INT NOT NULL,
  `produto_idpro` INT NOT NULL,
  `nmpro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvenda`),
  UNIQUE INDEX `idvenda_UNIQUE` (`idvenda` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cliente_iddi` ASC) VISIBLE,
  INDEX `fk_venda_produto1_idx` (`produto_idpro` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_iddi`)
    REFERENCES `mydb`.`cliente` (`idcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto1`
    FOREIGN KEY (`produto_idpro`)
    REFERENCES `mydb`.`produto` (`idpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_itens_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_itens_estoque` (
  `vendas_idvend` INT NOT NULL,
  `estoque_idest` INT NOT NULL,
  `qtd` INT NOT NULL,
  INDEX `fk_venda_has_estoque_estoque1_idx` (`vendas_idvend` ASC) VISIBLE,
  INDEX `fk_venda_has_estoque_vendas1_idx` (`estoque_idest` ASC) VISIBLE,
  CONSTRAINT `fk_venda_has_estoque_estoque1`
    FOREIGN KEY (`vendas_idvend`)
    REFERENCES `mydb`.`venda_copy1` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_estoque_vendas1`
    FOREIGN KEY (`estoque_idest`)
    REFERENCES `mydb`.`venda_copy1` (`produto_idpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idest` INT NOT NULL,
  `qtdest` INT NOT NULL,
  `vlest` DECIMAL(10) NOT NULL,
  `produto_idpro` INT NOT NULL,
  `idestoque` INT NOT NULL,
  PRIMARY KEY (`idest`, `produto_idpro`),
  UNIQUE INDEX `idestoque_UNIQUE` (`idestoque` ASC) VISIBLE,
  INDEX `fk_estoque_produto1_idx` (`produto_idpro` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`produto_idpro`)
    REFERENCES `mydb`.`produto` (`idpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `idcompra` INT not NULL,
  `fornecedor_idbr` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  UNIQUE INDEX `idcompra_UNIQUE` (`idcompra` ASC) VISIBLE,
  INDEX `fk_compra_fornecedor1_idx` (`fornecedor_idbr` ASC) VISIBLE,
  CONSTRAINT `fk_compra_fornecedor1`
    FOREIGN KEY (`fornecedor_idbr`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque_has_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque_has_compra` (
  `estoque_idest` INT NOT NULL,
  `compra_idcom` INT NOT NULL,
  INDEX `fk_estoque_has_compra_compra1_idx` (`compra_idcom` ASC) VISIBLE,
  PRIMARY KEY (`compra_idcom`, `estoque_idest`),
  INDEX `fk_estoque_has_compra_estoque_idx` (`estoque_idest` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_has_compra_compra1`
    FOREIGN KEY (`compra_idcom`)
    REFERENCES `mydb`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_has_compra_estoque`
    FOREIGN KEY (`estoque_idest`)
    REFERENCES `mydb`.`Estoque` (`idest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
