-- Script generated by Marcio Jose Santana RA 19102877-5
-- Sistema: Controle de Placa Version: 1.0


/* Criando o Banco de Dados do Sistema Controle de Placa */

create schema if not exists ExemploLivro ;

create table if not exists endereco (
	id_endereco int not null,
    cep int,
    logradouro varchar(45),
    numero int,
    complemento varchar(45)
    )engine = InnoDB;
    
create table if not exists pessoa (
	id_pessoa int not null,
    nome_pesosa varchar(45),
    sobrenome varchar(45),
    data_nascimento date
) engine = InnoDB;

create table if not exists telefone (
	id_telefone int not null,
    numero bigint(12) not null    
)engine = InnoDB;

create table if not exists pedido (
	id_pedido int not null
    
)engine = InnoDB;

create table if not exists pedido_item(
	desc_protudo int not null,
    valor decimal(3,2),
    qtde int not null,
    total decimal(3,2)
)engine = InnoDB;

alter table pessoa add primary key (id_pessoa);
alter table endereco add primary key (id_endereco);
alter table telefone add primary key (id_telefone);
alter table pedido add primary key(id_pedido);

alter table endereco add column id_pessoa int not null;
alter table telefone add column id_pessoa int not null;

alter table endereco add constraint pessoa_fk_endereco foreign key(id_pessoa) references pessoa(id_pessoa);
alter table telefone add constraint pessoa_fk_telefone foreign key(id_pessoa) references pessoa(id_pessoa);

alter table pedido add constraint pedido_fk_pessoa foreign key(id_pessoa) references pessoa(id_pessoa);
alter table pedido add constraint pedido_fk_endereco foreign key(id_endereco) references endereco(id_endereco);

enderecoalter table pedido_item add constraint pedido_fk_pedido foreign key(id_pedido) references pedido(id_pedido);

alter table pedido add column id_pessoa int not null;
alter table pedido add column id_endereco int not null;

alter table pedido_item add column id_pedido int not null;

insert into endereco (id_endereco, cep,logradouro,numero,complemento,id_pessoa) 
values (1, /*campo id_endereco*/ 
		86890880 ,/*campo cep*/ 
        'Av Paraná', /*Campo Logradouro*/ 
        27353, /*campo numero*/ 
        'Casa' ,/* Campo Complemento*/
        1); /*Campo id_pessoa Fk com a tabela de pessoa*/

insert into endereco (id_endereco, cep,logradouro,numero,complemento,id_pessoa) 
values (2, /*campo id_endereco*/ 
		86890880 ,/*campo cep*/ 
        'Av Brasil', /*Campo Logradouro*/ 
        412, /*campo numero*/ 
        'Sala 2 Comercial' ,/* Campo Complemento*/ 
        1); /*Campo id_pessoa Fk com a tabela de pessoa*/
        
    
insert into pessoa (id_pessoa,nome_pesosa,sobrenome,data_nascimento) 
values (1, /*Campo Id_pessoa*/
		'Joao', /*Campo Nome*/
		'Pereira', /*campo sobrenome*/
        '1983-09-15');/*campo data_nascimento*/

insert into telefone (id_telefone,numero,id_pessoa)
values (1, /*campo id_telefone*/
		4499786543, /*campo numero*/
        1); /*campo id_pessoa fk com a tabela pessoa*/
        
insert into telefone (id_telefone,numero,id_pessoa)
values (2, /*campo id_telefone*/
		4499786523, /*campo numero*/
        1); /*campo id_pessoa fk com a tabela pessoa*/
        
